# Generated by Django 2.2 on 2020-04-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OW', 'Outwear'), ('SW', 'Sport wear'), ('S', 'Shirt')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('I', 'info'), ('P', 'primary'), ('D', 'danger'), ('S', 'secondary')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
